
package gui;

import java.math.BigDecimal;
import static javax.swing.JOptionPane.showMessageDialog;
import oracleone.challenge2.Iniciador;
import oracleone.challenge2.Valores;

/**
 *
 * @author dante
 */
public class Longitud extends javax.swing.JPanel {

    /**
     * Creates new form Temperatura
     */
    public Longitud() {
        initComponents();
    }
    
    Iniciador iniciador;
    Valores valores;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecLong1 = new javax.swing.JComboBox<>();
        selecLong2 = new javax.swing.JComboBox<>();
        multLong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        resultLong = new javax.swing.JLabel();
        btnLong = new javax.swing.JButton();

        selecLong1.setBackground(java.awt.Color.lightGray);
        selecLong1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometros", "Metros", "Centimetros", "Milimetros", "Pulgadas", "Pies", "Yardas" }));
        selecLong1.setFocusable(false);
        selecLong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecLong1ActionPerformed(evt);
            }
        });

        selecLong2.setBackground(java.awt.Color.lightGray);
        selecLong2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilometros", "Metros", "Centimetros", "Milimetros", "Pulgadas", "Pies", "Yardas" }));
        selecLong2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecLong2ActionPerformed(evt);
            }
        });

        jLabel2.setText("a");

        resultLong.setBackground(new java.awt.Color(255, 255, 255));
        resultLong.setOpaque(true);

        btnLong.setText("Convertir");
        btnLong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selecLong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(multLong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(selecLong2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLong, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultLong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selecLong1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multLong, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecLong2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addComponent(btnLong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecLong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecLong1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecLong1ActionPerformed

    private void selecLong2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecLong2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecLong2ActionPerformed

    private void btnLongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLongActionPerformed
        try{
            iniciador = new Iniciador();
            valores = new Valores();

            String cantidadStr = multLong.getText();
            double cantidad = Double.parseDouble(cantidadStr);

            BigDecimal conversion = iniciador.objetosConv(selecLong1, selecLong2, valores.getValoresLong(WIDTH), cantidad);

            String resultadoFinal = conversion.toString();
            resultLong.setText(resultadoFinal);
        }catch(java.lang.NumberFormatException e){
            showMessageDialog(null, "No has introducido ningun valor");
            multLong.setText("");
            resultLong.setText("");
        }
    }//GEN-LAST:event_btnLongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField multLong;
    private javax.swing.JLabel resultLong;
    private javax.swing.JComboBox<String> selecLong1;
    private javax.swing.JComboBox<String> selecLong2;
    // End of variables declaration//GEN-END:variables
}
