/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.math.BigDecimal;
import static javax.swing.JOptionPane.showMessageDialog;
import oracleone.challenge2.ConvTemp;

/**
 *
 * @author dante
 */
public class Temperatura extends javax.swing.JPanel {

    /**
     * Creates new form Temperatura
     */
    public Temperatura() {
        initComponents();
    }
    
    ConvTemp temperatura;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecTemp1 = new javax.swing.JComboBox<>();
        multiTemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        selecTemp2 = new javax.swing.JComboBox<>();
        showResTemp = new javax.swing.JLabel();
        boton3 = new javax.swing.JButton();

        selecTemp1.setBackground(java.awt.Color.lightGray);
        selecTemp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius (ºC)", "Fahrenheit (ºF)", "Kelvin (K)" }));
        selecTemp1.setFocusable(false);
        selecTemp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecTemp1ActionPerformed(evt);
            }
        });

        jLabel2.setText("a");

        selecTemp2.setBackground(java.awt.Color.lightGray);
        selecTemp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius (ºC)", "Fahrenheit (ºF)", "Kelvin (K)" }));
        selecTemp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecTemp2ActionPerformed(evt);
            }
        });

        showResTemp.setBackground(new java.awt.Color(255, 255, 255));
        showResTemp.setOpaque(true);

        boton3.setText("Convertir");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(selecTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(multiTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(selecTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showResTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showResTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selecTemp1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecTemp2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selecTemp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecTemp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecTemp1ActionPerformed

    private void selecTemp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecTemp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecTemp2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        try{
            temperatura = new ConvTemp();

            String cantidadStr = multiTemp.getText();
            double cantidad = Double.parseDouble(cantidadStr);

            BigDecimal conversion = temperatura.objetosTemp(selecTemp1, selecTemp2, cantidad);

            String resultadoFinal = conversion.toString();
            showResTemp.setText(resultadoFinal);
        }catch(java.lang.NumberFormatException e){
            showMessageDialog(null, "No has introducido ningun valor");
            multiTemp.setText("");
            showResTemp.setText("");
        }
    }//GEN-LAST:event_boton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField multiTemp;
    private javax.swing.JComboBox<String> selecTemp1;
    private javax.swing.JComboBox<String> selecTemp2;
    private javax.swing.JLabel showResTemp;
    // End of variables declaration//GEN-END:variables
}
