
package gui;

import java.math.BigDecimal;
import static javax.swing.JOptionPane.showMessageDialog;
import oracleone.challenge2.Iniciador;
import oracleone.challenge2.Valores;

/**
 *
 * @author dante
 */
public class TipoCambio extends javax.swing.JPanel {

    /**
     * Creates new form TipoCambio
     */
    public TipoCambio() {
        initComponents();
    }
    
    Iniciador iniciador;
    Valores valores;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion1 = new javax.swing.JComboBox<>();
        seleccion2 = new javax.swing.JComboBox<>();
        multiplicador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        muestraResultado = new javax.swing.JLabel();
        boton1 = new javax.swing.JButton();

        seleccion1.setBackground(java.awt.Color.lightGray);
        seleccion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos Méxicanos", "Dólar EUA", "Euros", "Libras Esterlinas", "Yen Japonés", "Won sur-coreano" }));
        seleccion1.setFocusable(false);
        seleccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion1ActionPerformed(evt);
            }
        });

        seleccion2.setBackground(java.awt.Color.lightGray);
        seleccion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pesos Méxicanos", "Dólar EUA", "Euros", "Libras Esterlinas", "Yen Japonés", "Won sur-coreano" }));
        seleccion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccion2ActionPerformed(evt);
            }
        });

        jLabel2.setText("a");

        muestraResultado.setBackground(new java.awt.Color(255, 255, 255));
        muestraResultado.setOpaque(true);

        boton1.setText("Convertir");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(multiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(19, 19, 19)
                        .addComponent(seleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(boton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(muestraResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(muestraResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccion1ActionPerformed

    private void seleccion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccion2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        try{
            iniciador = new Iniciador();
            valores = new Valores();

            String cantidadStr = multiplicador.getText();
            double cantidad = Double.parseDouble(cantidadStr);

            BigDecimal conversion = iniciador.objetosConv(seleccion1, seleccion2, valores.getValoresDiv(WIDTH) , cantidad);

            String resultadoFinal = conversion.toString();
            muestraResultado.setText(resultadoFinal);
        }catch(java.lang.NumberFormatException e){
            showMessageDialog(null, "No has introducido ningun valor");
            multiplicador.setText("");
            muestraResultado.setText("");
        }
    }//GEN-LAST:event_boton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel muestraResultado;
    private javax.swing.JTextField multiplicador;
    private javax.swing.JComboBox<String> seleccion1;
    private javax.swing.JComboBox<String> seleccion2;
    // End of variables declaration//GEN-END:variables
}
